spring.application.name=WorkflowPortfolio
# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/workflow_db
spring.datasource.username=postgres
spring.datasource.password=kunnrenn

# MyBatis
mybatis.mapper-locations=classpath:com/example/workflowportfolio/mapper/**/*.xml
# Entityのパッケージ
mybatis.type-aliases-package=com.example.workflowportfolio

# 組み込みDB（H2など）以外のデータベース（PostgreSQLなど）でもschema.sqlを自動実行させる設定
spring.sql.init.mode=always
# data.sql も将来使う場合、テーブル作成（schema.sql）の完了を待ってから実行する設定
spring.sql.init.defer-datasource-initialization=false
# カラム自動変換
mybatis.configuration.map-underscore-to-camel-case=true